version: "3.8"

services:
  api:
    build: .
    container_name: recommendation-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
