name: Build and deploy Python project to Azure Function App - recom-contenu

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' 
  PYTHON_VERSION: '3.11' 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Vérifier la présence de host.json
        run: |
          if [ ! -f "host.json" ]; then
            echo '{}' > host.json
            echo "⚠️ host.json manquant, un fichier par défaut a été créé."
          fi

      - name: Vérifier la présence de requirements.txt
        run: |
          if [ ! -f "requirements.txt" ]; then
            echo "numpy" > requirements.txt
            echo "⚠️ requirements.txt manquant, un fichier minimal a été créé."
          fi

      - name: Installer les dépendances (dans wwwroot)
        run: |
          pip install -r requirements.txt -t .python_packages/lib/site-packages
          echo "✅ Dépendances installées"

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r -x "*.git*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write 
      contents: read 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip     

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E3F14F6BC9944635BF7C34FDCB59624C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_963E3A9B12D74A709C38D9DD28C46678 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0FB2FE9E9C7F4E0CB9F7314C9DF32CD9 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'recom-contenu'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Capture logs if deployment fails
        if: failure()
        run: |
          echo "❌ Le déploiement a échoué. Voici les logs :"
          cat /home/runner/.func/logs/*.log || echo "Aucun log trouvé."
