name: Deploy Azure Function - recom-contenu

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' 
  PYTHON_VERSION: '3.11' 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r -x ".git/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-package
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write 
      contents: read 

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: function-package

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'recom-contenu'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Capture logs on failure
        if: failure()
        run: |
          echo "Le déploiement a échoué. Logs :"
          cat /home/runner/.func/logs/*.log || echo "Aucun log trouvé."
